# Generated by Django 2.2.5 on 2019-10-18 09:15

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deeppages', '0003_page_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Unique template name. Relative path can be used, ie.: dashboard/index.html', max_length=100, unique=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('changed_at', models.DateTimeField(auto_now=True, verbose_name='Changed At')),
            ],
            options={
                'verbose_name': 'Template',
                'verbose_name_plural': 'Templates',
            },
        ),
        migrations.RemoveField(
            model_name='page',
            name='title',
        ),
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, editable=False, help_text='Unique identifier to be used on imports and other references', populate_from='name', unique=True),
        ),
    ]
